### ISSUE TITLE
The test FeatureCodeGeneration(browser: Chrome) fails randomly (OSOE-185)

### ISSUE THREAD

**Issue by dministro** [Lombiq/Helpful-Extensions#90]
Sometimes the `Lombiq.OSOCE.Tests.UI.Tests.BehaviorHelpfulExtensionsTests.FeatureCodeGeneration` fails on GH and TC too.
```
[xUnit.net 00:03:25.12]     Lombiq.OSOCE.Tests.UI.Tests.BehaviorHelpfulExtensionsTests.FeatureCodeGeneration(browser: Chrome) [FAIL]
  Failed Lombiq.OSOCE.Tests.UI.Tests.BehaviorHelpfulExtensionsTests.FeatureCodeGeneration(browser: Chrome) [54 s]
  Error Message:
   OpenQA.Selenium.StaleElementReferenceException : stale element reference: element is not attached to the page document
  (Session info: headless chrome=105.0.5195.102)
  Stack Trace:
     at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.get_Displayed()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Atata.ExtendedSearchContext`1.<>c__DisplayClass18_0.<Find>g__FindElementWithVisibilityFiltering|1(T context)
   at Atata.SafeWait`1.Until[TResult](Func`2 condition)
   at Atata.ExtendedSearchContext`1.Find(By by)
   at Lombiq.Tests.UI.Extensions.ElementRetrievalUITestContextExtensions.<>c__DisplayClass0_0.<Get>b__0() in D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Extensions\ElementRetrievalUITestContextExtensions.cs:line 29
...
```
[TC](https://ci.lombiq.com/viewLog.html?buildId=1092159&tab=buildResultsDiv&buildTypeId=OrchardExtensions_OSOCE_Developer_PullBuildTestNuGetSolution#testNameId-2571697762908198211)
[GH](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/8253304419?check_suite_focus=true)

**Comment by Piedone** [comment]
As evidenced by `show` being there in  `<div id="generated-migration-code-container" class="collapse show" style="">` in the HTML output, the code field is being shown, when the exception happens, it's not collapsed. That's sad, because the exception indicates it being collapsed, like two clicks happening on the toggle button.
